### ISSUE TITLE
Sklearn Dependency update to 1.4 instead of 1.3

### ISSUE THREAD

**Issue by DelongChenQC** [Quantco/metalearners#30]
In various places the following function from sklearn [root_mean_square_error](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html) is imported and used (e.g: [here](https://github.com/Quantco/metalearners/blob/2adf3af60867d10f9feb7a03cfb43255f562cc64/metalearners/tlearner.py#L6)). The function was added with version 1.4 hence the pyproject.toml should be updated from 1.3 to 1.4 to reflect this dependency. 

Would've liked to make a PR myself, but too much effort to understand how to get pixy pre-commit to run without documentation (to my understanding already work in progress :))

**Comment by kklein** [comment]
Great catch - thanks for pointing this out! :)

> but too much effort to understand how to get pixy pre-commit to run without documentation

Did you see this?
https://metalearners.readthedocs.io/en/latest/development.html#

**Comment by FrancescMartiEscofetQC** [comment]
> Did you see this?
> https://metalearners.readthedocs.io/en/latest/development.html#

Maybe we could add a link in the README for this so it's easier to find it?

**Comment by DelongChenQC** [comment]
>Did you see this?
https://metalearners.readthedocs.io/en/latest/development.html#

Nope, didn't see that 😅 . I think having a link in the readme or even the whole guide might be easier.
