### ISSUE TITLE
Remove git_root from run requirements?

### ISSUE THREAD

**Issue by jtilly** [Quantco/metalearners#42]
Does it make sense to have `git_root` as run requirement? If I install this package from PyPI or conda-forge, there's no guarantee that I'm running this inside a git repo. The only two helper functions inside the package that use `git_root` are
- https://github.com/Quantco/metalearners/blob/60745dc284980f60f129cbef443570bd2acd6b5b/metalearners/_utils.py#L329
- https://github.com/Quantco/metalearners/blob/60745dc284980f60f129cbef443570bd2acd6b5b/metalearners/_utils.py#L365

Here you can just add an argument that tells the functions where to download the data to. If you remove `git_root` there, it's just a development requirement afterwards.

**Comment by kklein** [comment]
Very good points - we should do this!
