### ISSUE TITLE
Evaluate method fails if feature_set is not None

### ISSUE THREAD

**Issue by ArseniyZvyagintsevQC** [Quantco/metalearners#65]
Initialize X, R, or DR metalearner with feature_set specifying what columns are used for what base models
Fit it
Evaluate it

Evaluation fails with an error "Number of features must match the input..."

**Comment by FrancescMartiEscofetQC** [comment]
Thanks for catching it! It should be fixed in #66 . It will come with version 0.8.0 next week.
